version: '3'

services:
  web:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./src/public:/app/public:ro
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:ro

  php:
    image: docker-example-php
    build: docker/php

    working_dir: /app

    volumes:
      - ./src:/app:cached

  mysql:
    image: mysql
    ports:
      - 3306
    environment:
      MYSQL_DATABASE: example
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: 'true'
    volumes:
      - db:/var/lib/mysql

volumes:
  db:
