version: '3'

services:

  web:
    networks:
      - default
      - backend

  php:
    networks:
      - backend

  mysql:
    networks:
      - backend

    environment: {}

networks:
  default:
  backend:
