easy_admin:
    site_name: 'Gallery'
    user:
        display_name: true
        name_property_path: email

    entities:
        # List the entity class name you want to manage
        Images:
            class: App\Entity\Image
            list:
                fields:
                    - id
                    - title
                    - description
                    - { property: 'filename', type: 'image', base_path: '%app.path.images%' }
            show:
                fields:
                    - id
                    - title
                    - description
                    - { property: 'filename', type: 'image', base_path: '%app.path.images%' }
                    - createdAt
                    - updatedAt
            form:
                fields:
                    - title
                    - description
                    - { property: 'imageFile', type: 'vich_image' }
        User:
            class: App\Entity\User
